# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaeeab08a0c578ef56de3cb1523b60fdbe3eedf29f8a607aa8a68020a251b7f0c9b156b7acbf06edcaf2e7460472d06bfca1f35a454367dd7384d0f7b51eb007

test:
  secret_key_base: abc9253c01d8b3b42f54baf3f1558d3cfe1288fe2bfdf15014389be2e3e9e986973140f5f46fca2e07e0d37e61a054ad464ce06a12cd5ff4eeacb7a95ac07182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
